### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by LaGordaRacista** [Brandcraf06/NetherThings#19]
---- Minecraft Crash Report ----
// My bad.

Time: 2020-01-11 13:09:32 GMT-04:00
Description: Initializing game

java.lang.RuntimeException: Could not execute entrypoint stage 'client' due to errors!
    at Not Enough Crashes deobfuscated stack trace.(1.15.1+build.32)
    at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:55)
    at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke(EntrypointUtils.java:34)
    at net.minecraft.client.MinecraftClient.redirect$zcc000$stopFabricInit(MinecraftClient:3487)
    at net.minecraft.client.MinecraftClient.<init>(MinecraftClient:391)
    at net.minecraft.client.main.Main.main(Main:164)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:193)
    at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:138)
    at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
    Suppressed: java.lang.NoClassDefFoundError: net/fabricmc/fabric/api/client/render/EntityRendererRegistry
        at com.brand.netherthings.NetherThingsClient.onInitializeClient(NetherThingsClient.java:15)
        at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:48)
        ... 11 more
    Caused by: java.lang.ClassNotFoundException: net.fabricmc.fabric.api.client.render.EntityRendererRegistry
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:161)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        ... 13 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Initialization --

-- System Details --
  Minecraft Version: 1.15.1
  Minecraft Version ID: 1.15.1
  Operating System: Windows 7 (x86) version 6.1
  Java Version: 1.8.0_221, Oracle Corporation
  Java VM Version: Java HotSpot(TM) Client VM (mixed mode), Oracle Corporation
  Memory: 128521936 bytes (122 MB) / 442290176 bytes (421 MB) up to 1060372480 bytes (1011 MB)
  CPUs: 2
  JVM Flags: 5 total; -Xmn128M -Xmx1024M -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -XX:+UseConcMarkSweepGC
  Suspected Mods: Fabric Loader (fabricloader), Nether Things (netherthings)
  Fabric Mods: adorn: Adorn 1.6.5+1.15.1
               autoconfig1: Auto Config v1 1.1.2+mc1.14.1
               autoconfig1u: Auto Config v1 Updated 1.2.4
               cloth: Cloth Events 1.1.0
               cloth-config2: Cloth Config v2 2.6.5
               fabric: Fabric API 0.4.27+build.286-1.15
               fabric-api-base: Fabric API Base 0.1.2+b7f9825d95
               fabric-biomes-v1: Fabric Biomes (v1) 0.1.5+3b05f68e95
               fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.4+c6a8ea8995
               fabric-commands-v0: Fabric Commands (v0) 0.1.2+b7f9825d95
               fabric-containers-v0: Fabric Containers (v0) 0.1.3+b7f9825d95
               fabric-content-registries-v0: Fabric Content Registries (v0) 0.1.3+b7f9825d95
               fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.2+b7f9825d95
               fabric-dimensions-v1: fabric-dimensions-v1 0.2.3+06c939b395
               fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.2.7+a1bd311895
               fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.1.2+b7f9825d95
               fabric-furnaces: Fabric Furnaces 1.2.0
               fabric-item-groups-v0: Fabric Item Groups (v0) 0.1.6+ec40b2e195
               fabric-keybindings-v0: Fabric Key Bindings (v0) 0.1.1+dfdb52d695
               fabric-language-kotlin: Fabric Language Kotlin 1.3.61+build.1
               fabric-loot-tables-v1: Fabric Loot Tables (v1) 0.1.5+e08a730595
               fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.1+b7f9825d95
               fabric-models-v0: Fabric Models (v0) 0.1.0+dfdb52d695
               fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.3+e08a730595
               fabric-networking-v0: Fabric Networking (v0) 0.1.7+12515ed995
               fabric-object-builders-v0: Fabric Object Builders (v0) 0.1.3+e4c9a9c395
               fabric-particles-v1: fabric-particles-v1 0.1.1+dfdb52d695
               fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.2.6+f3d8141b95
               fabric-renderer-api-v1: Fabric Renderer API (v1) 0.2.7+f3d8141b95
               fabric-renderer-indigo: Fabric Renderer - Indigo 0.2.21+175d0eb895
               fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 2.0.1+5a0f9a6095
               fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.3+b7f9825d95
               fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.6+12515ed995
               fabric-rendering-v0: Fabric Rendering (v0) 1.1.0+5341049095
               fabric-rendering-v1: Fabric Rendering (v1) 0.1.0+5341049095
               fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.1.10+06c939b395
               fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 0.1.3+abd9158095
               fabric-textures-v0: Fabric Textures (v0) 1.0.4+821cdba795
               fabricloader: Fabric Loader 0.7.3+build.176
               jankson: Jankson 2.0.1+j1.2.0
               libcd: LibCapableData 1.6.2+1.15
               libgui: LibGui 1.3.3-beta.7
               loadcatcher: Entrypoint Catcher 1.1.0
               minecraft: Minecraft 1.15.1
               mobz: MobZ 1.9.0
               nbtcrafting: NBT Crafting 1.2.11+1.15.1
               netherthings: Nether Things 1.2.0
               notenoughcrashes: Not Enough Crashes 1.2.0+1.15.1
               org_jetbrains_annotations: annotations 17.0.0
               org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.3.61
               org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.3.61
               org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.3.61
               org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.3.61
               org_jetbrains_kotlinx_kotlinx-coroutines-core: kotlinx-coroutines-core 1.3.3
               org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.3.3
               roughlyenoughitems: Roughly Enough Items 3.3.8
               terraform: Terraform 1.3.4+build.17
               terrestria: Terrestria 1.1.1+build.18
               traverse: Traverse 2.1.7+build.15
               trees-do-not-float: Trees Do Not Float 1.8.69
  Launched Version: 1.15.1
  Backend library: LWJGL version 3.2.2 build 10
  Backend API: NO CONTEXT
  GL Caps: 
  Using VBOs: Yes
  Is Modded: Definitely; Client brand changed to 'fabric'
  Type: Client (map_client.txt)
  CPU: <unknown>

**Comment by Brandcraf06** [comment]
The mod isn't compatible with 1.15 and 1.15.1
